### ISSUE TITLE
Not working for Users-Permissions plugin routes.

### ISSUE THREAD

**Issue by webmatrixxxl** [Barelydead/strapi-plugin-populate-deep#4]
Hello! It is not working for the Users-Permissions plugin routes. Can it be applied there too?

**Comment by Barelydead** [comment]
Hi @webmatrixxxl, I belive this might be casued by a core issue that resently been resolved in the new version, [4.1.1 release](https://forum.strapi.io/t/new-release-strapi-v4-1-10/18485). I havent tried it myself but please let me know if you find it works on the later versions of strapi.

**Comment by webmatrixxxl** [comment]
@Barelydead, Yes. That is right!  `users/me` is still not populating and we have opened issue about it here: [https://github.com/strapi/strapi/issues/13296](https://github.com/strapi/strapi/issues/13296)
